export { default as Home } from './Home'
export { default as Cart } from './Cart'
export { default as Login } from './Login'
export { default as Registration } from './Registration'
export { default as Book } from './Book'
export { default as Profile } from './Profile'
export { default as PageNotFound } from './PageNotFound'